import { AnomalyPreset, TelemetryIncident, AgentStatus, InterventionLedgerItem } from '../types';

export const ANOMALY_PRESETS: AnomalyPreset[] = [
  {
    id: 'thermal',
    presetNum: 'PRESET 01 // EPS',
    subsystem: 'EPS THERMAL',
    title: 'Thermal Runaway',
    description: 'Battery loop valve failure & passive dissipation stall',
    severityDefault: 3,
    severityLabel: 'LEVEL 3 // CRITICAL (78%)',
    detectionTime: 2.4,
    mitigationTime: 4.1,
    recoveryTime: 11.8,
    baselineMetric: '21.2 °C',
    faultMetric: '48.9 °C',
    remediatedMetric: '22.8 °C',
    deltaSummary: 'Peak temp: 48.9°C → 22.8°C (99.4% saved)',
    telemetryChannel: 'EPS Battery Cell #3 / Heat Pipe Loop #2',
    journalLogs: [
      {
        time: '+00:00.00',
        agent: 'CHAOS_ENGINE',
        tag: 'FAULT_INJECT',
        tagColor: 'bg-tertiary/20 text-tertiary',
        message: 'Chaos test packet: #CHAOS-LOOP-FAIL-2 injected into EPS Subsystem SIM.',
      },
      {
        time: '+00:00.32',
        agent: 'Agent-Alpha::Thermal',
        tag: 'OBSERVE',
        tagColor: 'bg-primary/20 text-primary',
        message: 'Anomaly alert: Battery cell #03 delta-T rate +1.4°C/sec exceeding safety threshold (30.0°C).',
      },
      {
        time: '+00:01.17',
        agent: 'Agent-Delta::FDIR',
        tag: 'CROSS-CHECK',
        tagColor: 'bg-primary-fixed/20 text-primary-fixed',
        message: 'Fault Isolation: Solenoid valve SV-04 mechanical jam diagnosed in loop #1. Passively degraded.',
      },
      {
        time: '+00:02.37',
        agent: 'SWARM_CONSENSUS',
        tag: 'CONSENSUS',
        tagColor: 'bg-secondary/20 text-secondary',
        message: 'Plan signed across {EPS_CORE, AOCS_GUIDE, THERMAL_MGR, COMM_RELAY}. Quorum reached (4/4 in 8.2ms).',
      },
      {
        time: '+00:04.10',
        agent: 'Agent-Beta::AOCS',
        tag: 'DISPATCH',
        tagColor: 'bg-primary text-on-primary',
        message: '>> Slew roll axis -12.0° to shade radiator from Earth albedo. Auxiliary heat pipe bypass engaged.',
      },
      {
        time: '+00:07.82',
        agent: 'Agent-Alpha::Thermal',
        tag: 'VERIFY',
        tagColor: 'bg-secondary/20 text-secondary',
        message: 'Battery temperature gradient stabilized at 32.1°C. Inversion verified (-0.6°C/sec cooling rate).',
      },
      {
        time: '+00:11.80',
        agent: 'SWARM_CONSENSUS',
        tag: 'REMEDIATED',
        tagColor: 'bg-secondary text-on-secondary',
        message: 'Closed-loop recovery verified. System returned to nominal operating flight envelope (22.8°C).',
      },
    ],
  },
  {
    id: 'adcs',
    presetNum: 'PRESET 02 // ADCS',
    subsystem: 'AOCS ATTITUDE',
    title: 'Attitude Drift & Desync',
    description: 'Gyro desynchronization & reaction wheel saturation',
    severityDefault: 2,
    severityLabel: 'LEVEL 2 // MODERATE (50%)',
    detectionTime: 1.8,
    mitigationTime: 3.6,
    recoveryTime: 9.4,
    baselineMetric: '0.00° / 0.001 rad',
    faultMetric: '+14.2°/s drift',
    remediatedMetric: '< 0.003° residual',
    deltaSummary: 'Rate error: +14.2°/s → 0.002°/s (Null torque restored)',
    telemetryChannel: 'ADCS 3-Axis Gyros & RW-1/RW-2/RW-3 Speeds',
    journalLogs: [
      {
        time: '+00:00.00',
        agent: 'CHAOS_ENGINE',
        tag: 'FAULT_INJECT',
        tagColor: 'bg-tertiary/20 text-tertiary',
        message: 'Inject synthetic gyro noise bias (+0.85 rad/s) on roll & pitch IMU sensor bus.',
      },
      {
        time: '+00:00.41',
        agent: 'Agent-Beta::AOCS',
        tag: 'OBSERVE',
        tagColor: 'bg-primary/20 text-primary',
        message: 'Attitude quaternion divergence detected. Gyro reading disagrees with star tracker STR-1 by 4.8°.',
      },
      {
        time: '+00:01.20',
        agent: 'Agent-Delta::FDIR',
        tag: 'CROSS-CHECK',
        tagColor: 'bg-primary-fixed/20 text-primary-fixed',
        message: 'Kalman residual filter triggered. Rejecting primary IMU gyro packet; switching to STR optical solution.',
      },
      {
        time: '+00:02.10',
        agent: 'SWARM_CONSENSUS',
        tag: 'CONSENSUS',
        tagColor: 'bg-secondary/20 text-secondary',
        message: 'Multi-agent vote unanimous: Engage magnetorquer cross-coupling and RW counter-torque pulse.',
      },
      {
        time: '+00:03.60',
        agent: 'Agent-Beta::AOCS',
        tag: 'DISPATCH',
        tagColor: 'bg-primary text-on-primary',
        message: 'RW-2 counter-torque pulse (+0.18 N·m) commanded. Nadir Earth horizon lock re-acquired.',
      },
      {
        time: '+00:09.40',
        agent: 'SWARM_CONSENSUS',
        tag: 'REMEDIATED',
        tagColor: 'bg-secondary text-on-secondary',
        message: '3-Axis pointing error converged to 0.0028°. Earth observing optical target aligned.',
      },
    ],
  },
  {
    id: 'drag',
    presetNum: 'PRESET 03 // ORBIT',
    subsystem: 'ORBITAL MECHANICS',
    title: 'Atmospheric Drag Decay',
    description: 'Solar flare thermospheric expansion decay vector',
    severityDefault: 3,
    severityLabel: 'LEVEL 3 // CRITICAL (78%)',
    detectionTime: 3.1,
    mitigationTime: 5.4,
    recoveryTime: 14.2,
    baselineMetric: '541.80 km',
    faultMetric: '-128m orbital dip',
    remediatedMetric: '541.98 km (Restored)',
    deltaSummary: 'Altitude loss: -128m corrected (+0.14 m/s ΔV burn)',
    telemetryChannel: 'GPS Ephemeris & Semi-Major Axis Filter',
    journalLogs: [
      {
        time: '+00:00.00',
        agent: 'CHAOS_ENGINE',
        tag: 'FAULT_INJECT',
        tagColor: 'bg-tertiary/20 text-tertiary',
        message: 'Atmospheric density perturbation +340% injected simulating coronal mass ejection shockwave.',
      },
      {
        time: '+00:00.88',
        agent: 'Agent-Gamma::Prop',
        tag: 'OBSERVE',
        tagColor: 'bg-tertiary/20 text-tertiary',
        message: 'Semi-major axis rate of decay accelerating (-0.04 m/s²). Projected perigee dip -128m in 4 orbits.',
      },
      {
        time: '+00:02.15',
        agent: 'Agent-Delta::FDIR',
        tag: 'CROSS-CHECK',
        tagColor: 'bg-primary-fixed/20 text-primary-fixed',
        message: 'Correlating with space weather UV sensor flux. Confirmed thermospheric bulge; aerodynamic drag active.',
      },
      {
        time: '+00:03.90',
        agent: 'SWARM_CONSENSUS',
        tag: 'CONSENSUS',
        tagColor: 'bg-secondary/20 text-secondary',
        message: 'Pre-schedule micro-pulse apogee burn sequence. Propellant consumption budget: 14.8 grams hydrazine.',
      },
      {
        time: '+00:05.40',
        agent: 'Agent-Gamma::Prop',
        tag: 'DISPATCH',
        tagColor: 'bg-primary text-on-primary',
        message: '>> RCS Pod 1 & 2 dual-pulse fired (+0.14 m/s ΔV). Apogee station-keeping vector established.',
      },
      {
        time: '+00:14.20',
        agent: 'SWARM_CONSENSUS',
        tag: 'REMEDIATED',
        tagColor: 'bg-secondary text-on-secondary',
        message: 'Orbital velocity restored to Mach 22.4. Ephemeris orbit height nominal at 541.98 km.',
      },
    ],
  },
  {
    id: 'thruster',
    presetNum: 'PRESET 04 // PROP',
    subsystem: 'PROPULSION RCS',
    title: 'Thruster Sticking & Asymmetry',
    description: 'Asymmetric RCS pulse burn & yaw axis coupling',
    severityDefault: 4,
    severityLabel: 'LEVEL 4 // CATASTROPHIC (100%)',
    detectionTime: 0.9,
    mitigationTime: 2.1,
    recoveryTime: 8.5,
    baselineMetric: 'Zero thrust idle',
    faultMetric: '+3.8 N continuous',
    remediatedMetric: 'Valve isolated / 0 N',
    deltaSummary: 'Yaw rate: +8.4°/s arrested via counter-thruster fire',
    telemetryChannel: 'Hydrazine Manifold Pressure & RCS Pod 2 Flow',
    journalLogs: [
      {
        time: '+00:00.00',
        agent: 'CHAOS_ENGINE',
        tag: 'FAULT_INJECT',
        tagColor: 'bg-error/20 text-error',
        message: 'RCS Pod 2 micro-valve commanded stuck open at 100% flow.',
      },
      {
        time: '+00:00.28',
        agent: 'Agent-Delta::FDIR',
        tag: 'OBSERVE',
        tagColor: 'bg-error text-on-error',
        message: 'CRITICAL: Uncommanded asymmetric thrust detected on Pod 2! Manifold pressure dipping 0.4 bar/s.',
      },
      {
        time: '+00:00.75',
        agent: 'Agent-Beta::AOCS',
        tag: 'COUNTER-ACT',
        tagColor: 'bg-primary text-on-primary',
        message: 'Immediately firing opposing RCS Pod 4 counter-burst to nullify induced yaw angular momentum.',
      },
      {
        time: '+00:01.40',
        agent: 'Agent-Gamma::Prop',
        tag: 'HARD-ISOLATE',
        tagColor: 'bg-error text-on-error',
        message: 'Hardware pyro-valve PV-02 triggered. Pod 2 line sealed. Propellant depletion halted at 85.9% reserve.',
      },
      {
        time: '+00:08.50',
        agent: 'SWARM_CONSENSUS',
        tag: 'REMEDIATED',
        tagColor: 'bg-secondary text-on-secondary',
        message: 'Rotational rates settled. Safe flight envelope preserved using redundant Pod 1 & 3 configuration.',
      },
    ],
  },
  {
    id: 'sada',
    presetNum: 'PRESET 05 // SOLAR',
    subsystem: 'SOLAR SADA',
    title: 'SADA Gimbal Stall',
    description: 'Drive actuator lock at -38° off sun-pointing locus',
    severityDefault: 2,
    severityLabel: 'LEVEL 2 // MODERATE (50%)',
    detectionTime: 2.2,
    mitigationTime: 4.8,
    recoveryTime: 10.2,
    baselineMetric: '2,420 W (99.8% eff)',
    faultMetric: '1,490 W (-38° angle)',
    remediatedMetric: '2,380 W (Restored)',
    deltaSummary: 'Power generation restored via satellite body slew angle',
    telemetryChannel: 'SADA Stepper Motor Current & EPS Bus Volts',
    journalLogs: [
      {
        time: '+00:00.00',
        agent: 'CHAOS_ENGINE',
        tag: 'FAULT_INJECT',
        tagColor: 'bg-tertiary/20 text-tertiary',
        message: 'Solar array drive assembly stepper stall injected at -38° off sun vector.',
      },
      {
        time: '+00:00.64',
        agent: 'Agent-Alpha::Thermal',
        tag: 'OBSERVE',
        tagColor: 'bg-primary/20 text-primary',
        message: 'EPS Solar Alpha harvest dropped to 1,490W. Solar incident angle efficiency degraded by 38.5%.',
      },
      {
        time: '+00:01.80',
        agent: 'Agent-Delta::FDIR',
        tag: 'DIAGNOSTIC',
        tagColor: 'bg-primary-fixed/20 text-primary-fixed',
        message: 'Stepper current spike indicates mechanical gear friction in gimbal Alpha yoke.',
      },
      {
        time: '+00:03.20',
        agent: 'Agent-Beta::AOCS',
        tag: 'PROPOSAL',
        tagColor: 'bg-secondary/20 text-secondary',
        message: 'Compensate SADA stall by offsetting entire satellite body yaw angle by +38° to align panels with sun.',
      },
      {
        time: '+00:10.20',
        agent: 'SWARM_CONSENSUS',
        tag: 'REMEDIATED',
        tagColor: 'bg-secondary text-on-secondary',
        message: 'Solar output restored to 2,380W (+410W bus surplus). Battery SOC charging nominal.',
      },
    ],
  },
  {
    id: 'collision',
    presetNum: 'PRESET 06 // KINETIC',
    subsystem: 'COLLISION & TRAJECTORY',
    title: 'Space Object Collision & Trajectory Recovery',
    description: 'Orbital debris kinetic impact, altitude drop & corrective ΔV burn',
    severityDefault: 3,
    severityLabel: 'LEVEL 3 // KINETIC IMPACT (78%)',
    detectionTime: 1.6,
    mitigationTime: 4.5,
    recoveryTime: 12.2,
    baselineMetric: '541.80 km (Nominal Orbit)',
    faultMetric: '534.20 km (-7.6 km altitude drop)',
    remediatedMetric: '541.78 km (Orbit Restored)',
    deltaSummary: 'Altitude drop: -7.6 km corrected via prograde burn (+4.2 m/s ΔV)',
    telemetryChannel: 'GPS Ephemeris Altitude & IMU Kinetic Shockwave',
    journalLogs: [
      {
        time: '+00:00.00',
        agent: 'CHAOS_ENGINE',
        tag: 'FAULT_INJECT',
        tagColor: 'bg-rose-500/20 text-rose-400',
        message: 'Space object collision scenario loaded. Tracking incoming debris fragment OBJ-49211 (2.4cm @ 11.2 km/s).',
      },
      {
        time: '+00:01.60',
        agent: 'CHAOS_ENGINE',
        tag: 'COLLISION_IMPACT',
        tagColor: 'bg-rose-500 text-white font-bold',
        message: '>> IMPACT DETECTED! Space debris strikes satellite starboard bus. Instantaneous impulse shockwave registered on IMU.',
      },
      {
        time: '+00:01.85',
        agent: 'Agent-Beta::AOCS',
        tag: 'CRITICAL_ALERT',
        tagColor: 'bg-rose-500/20 text-rose-400',
        message: 'Kinetic momentum imparted! Orbit altitude plummeting from 541.80 km to 534.20 km (-7.6 km perigee drop). Induced tumble rate: +18.4°/s.',
      },
      {
        time: '+00:02.60',
        agent: 'Agent-Delta::FDIR',
        tag: 'DAMAGE_ASSESS',
        tagColor: 'bg-amber-400/20 text-amber-300',
        message: 'Whipple shield breached; bus structural integrity nominal. Trajectory deviation requires active orbital station-keeping burn.',
      },
      {
        time: '+00:03.40',
        agent: 'SWARM_CONSENSUS',
        tag: 'CONSENSUS',
        tagColor: 'bg-secondary/20 text-secondary',
        message: 'Swarm computes trajectory correction vector. Approving +4.2 m/s prograde apogee burn to restore circular 541.8 km orbit.',
      },
      {
        time: '+00:04.50',
        agent: 'Agent-Gamma::Prop',
        tag: 'DISPATCH',
        tagColor: 'bg-primary text-on-primary',
        message: '>> Thruster Bank A & B firing prograde (+4.2 m/s ΔV burn). Orbit altitude ascending back toward 541.8 km.',
      },
      {
        time: '+00:12.20',
        agent: 'SWARM_CONSENSUS',
        tag: 'REMEDIATED',
        tagColor: 'bg-secondary text-on-secondary',
        message: 'Trajectory circularized. Orbital altitude stabilized at 541.78 km. Kinetic collision error fully remediated.',
      },
    ],
  },
];

export const INITIAL_AGENTS: AgentStatus[] = [
  {
    id: 'alpha',
    name: 'Agent Alpha',
    subsystem: 'PWR & THERMAL',
    role: 'Thermal loop balancing & EPS voltage optimization',
    state: 'active_correction',
    isolated: false,
    confidence: 99.7,
    description: 'Evaluating Battery Cell #4 Heat Spike. Monitoring +0.4°C/min inflection gradient.',
  },
  {
    id: 'beta',
    name: 'Agent Beta',
    subsystem: 'ATTITUDE & ORBIT',
    role: 'AOCS 3-axis pointing & reaction wheel momentum',
    state: 'balancing',
    isolated: false,
    confidence: 99.98,
    description: 'Reaction wheel RW-2 torque pulse initiated. Pre-cessional error delta < 0.003°.',
  },
  {
    id: 'gamma',
    name: 'Agent Gamma',
    subsystem: 'PROPULSION & SK',
    role: 'Apogee delta-V drag compensation & RCS burn planning',
    state: 'standby',
    isolated: false,
    confidence: 99.85,
    description: 'Awaiting Next Apogee Station-keeping node (T-02:44:18). Fuel reserves: 88.4%.',
  },
  {
    id: 'delta',
    name: 'Agent Delta',
    subsystem: 'FDIR HEURISTICS',
    role: 'Fault detection, isolation & multi-agent quorum verification',
    state: 'nominal',
    isolated: false,
    confidence: 99.99,
    description: 'Cross-sensor verification running. 0 unmitigated hardware anomalies across bus.',
  },
];

export const INITIAL_LEDGER_ITEMS: InterventionLedgerItem[] = [
  {
    id: 'led-1',
    timestamp: '14:02:11.61',
    leadAgent: 'Beta (AOCS)',
    actionExecuted: 'Roll slew +4.2° for thermal shade',
    resolutionTime: '1.8s',
    telemetryDelta: '-3.5°C Batt-4 temp',
  },
  {
    id: 'led-2',
    timestamp: '13:48:02.19',
    leadAgent: 'Alpha (Thermal)',
    actionExecuted: 'Heater Loop #2 cycle throttle (50% → 35%)',
    resolutionTime: '0.9s',
    telemetryDelta: '-4.2W power draw',
  },
  {
    id: 'led-3',
    timestamp: '11:15:33.80',
    leadAgent: 'Delta (FDIR)',
    actionExecuted: 'Star Tracker STR-1 single-event upset reboot',
    resolutionTime: '3.2s',
    telemetryDelta: 'Parity restored',
  },
  {
    id: 'led-4',
    timestamp: '09:30:14.05',
    leadAgent: 'Gamma (Prop)',
    actionExecuted: 'Thruster Cat-Bed preheating pulse sequence',
    resolutionTime: '2.1s',
    telemetryDelta: '+120°C nozzle readiness',
  },
];

export const INITIAL_INCIDENTS: TelemetryIncident[] = [
  {
    id: 'EV-9821',
    subsystem: 'THERMAL',
    type: 'REAL',
    triggerRoot: 'Cell 6 Thermal Spike >28°C',
    responseTime: '142 ms',
    remediator: 'Agent-Therma-4',
    status: 'RESOLVED',
  },
  {
    id: 'EV-9804',
    subsystem: 'ADCS',
    type: 'CHAOS',
    triggerRoot: 'Star Tracker 2 Glare Blindness',
    responseTime: '88 ms',
    remediator: 'Agent-Attitude-1',
    status: 'RESOLVED',
  },
  {
    id: 'EV-9788',
    subsystem: 'PROPULSION',
    type: 'REAL',
    triggerRoot: 'RCS Valve 3 Jitter (2.1bar)',
    responseTime: '210 ms',
    remediator: 'Agent-Prop-2',
    status: 'RESOLVED',
  },
  {
    id: 'EV-9762',
    subsystem: 'COMM-RF',
    type: 'CHAOS',
    triggerRoot: 'Synthetic S-Band Bit Flip',
    responseTime: '44 ms',
    remediator: 'Agent-Comm-Crypto',
    status: 'RESOLVED',
  },
  {
    id: 'EV-9730',
    subsystem: 'EPS POWER',
    type: 'REAL',
    triggerRoot: 'Array Wing-B Eclipse Hysteresis',
    responseTime: '310 ms',
    remediator: 'Agent-Power-3',
    status: 'RESOLVED',
  },
];
